# Generated by Django 2.2.6 on 2020-01-01 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200101_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='picture',
            field=models.ImageField(blank=True, default='default/default.jpg', null=True, upload_to='pictures/'),
        ),
    ]
