# Generated by Django 2.2.6 on 2020-01-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200102_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date_pub',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
