# Generated by Django 2.2.6 on 2020-01-02 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200102_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_liked',
        ),
    ]
